# https://docs.docker.com/compose/compose-file/
version: "3.3"

services:
  db_master5:
    image: mariadb:10.6.3-focal
    container_name: db_master5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mariadb_root_password
    volumes:
      - ./master/data:/var/lib/mysql
      - ./master/config/:/etc/mysql/conf.d
      - ./master/mysql-init-files/:/docker-entrypoint-initdb.d/
    ports:
      - "33310:3306"
    secrets:
      - mariadb_root_password

  db_slave5:
    image: mariadb:10.6.3-focal
    container_name: db_slave5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mariadb_root_password
    volumes:
      - ./slave/data:/var/lib/mysql
      - ./slave/config/:/etc/mysql/conf.d
      - ./slave/mysql-init-files/:/docker-entrypoint-initdb.d/
    ports:
      - "43310:3306"
    secrets:
      - mariadb_root_password
    depends_on:
      - db_master5
    
secrets:
  mariadb_root_password:
    file: mariadb_root_password.txt
